# This file was generated by GoReleaser. DO NOT EDIT.
cask "cli-t" do
  version "1.0.1"

  on_macos do
    on_intel do
      sha256 "4b566c904223ec64447ffee570bc64548bf9e59eff9104c08a49747b69a1035c"
      url "https://github.com/sleipi/cli-t/releases/download/v#{version}/cli-t_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "04451c999936d0e32a4d6f2e20987556c49ccbb3b800dae3cd8eebfc0926151d"
      url "https://github.com/sleipi/cli-t/releases/download/v#{version}/cli-t_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "1f3a60fa2e07aba9e82ebb9f34ac8c090c0b6b3082582a66c327e0e2f39b4206"
      url "https://github.com/sleipi/cli-t/releases/download/v#{version}/cli-t_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "aba088e5f320928dfa4051c38e335cfe60984f3995e20434abdcb1b4c5d8c5f9"
      url "https://github.com/sleipi/cli-t/releases/download/v#{version}/cli-t_#{version}_linux_arm64.tar.gz"
    end
  end

  name "cli-t"
  desc "Declarative CLI testing tool"
  homepage "https://github.com/sleipi/cli-t"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "clitest"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/clitest"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    CLITest installed! Run 'clitest' to start.
  EOS
end
