# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CliT < Formula
  desc "Declarative CLI testing tool"
  homepage "https://github.com/sleipi/cli-t"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sleipi/cli-t/releases/download/v1.0.0/cli-t_1.0.0_darwin_amd64.tar.gz"
      sha256 "b2fc0d53c81864c4faebcff3b57d9cbff33670d19fc86cdb18c117f50b7320e0"

      define_method(:install) do
        bin.install "clitest"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sleipi/cli-t/releases/download/v1.0.0/cli-t_1.0.0_darwin_arm64.tar.gz"
      sha256 "a65409287bc2f42435c4e6a99ee0d442e0f840c6ab99dec33afe2d0bfd697728"

      define_method(:install) do
        bin.install "clitest"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sleipi/cli-t/releases/download/v1.0.0/cli-t_1.0.0_linux_amd64.tar.gz"
      sha256 "b6f1f42c48ec0ce126186eae10e3be6937a715a4565c1e6ec4054fab16099b44"
      define_method(:install) do
        bin.install "clitest"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sleipi/cli-t/releases/download/v1.0.0/cli-t_1.0.0_linux_arm64.tar.gz"
      sha256 "45dd047fdd3d32acc0fd18e33619a04c998e88a63371a542612f1e70b3931bbf"
      define_method(:install) do
        bin.install "clitest"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/clitest --version")
  end
end
