# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CliT < Formula
  desc "Declarative CLI testing tool"
  homepage "https://github.com/sleipi/cli-t"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sleipi/cli-t/releases/download/v1.0.0/cli-t_1.0.0_darwin_amd64.tar.gz"
      sha256 "631e543837a17e45e93f81e5e4225940bb322ca37342cf43535c542affd68048"

      define_method(:install) do
        bin.install "clitest"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sleipi/cli-t/releases/download/v1.0.0/cli-t_1.0.0_darwin_arm64.tar.gz"
      sha256 "8eaa8d270d58f4827d915ed85cc5fb5d2ce62e31714fa3ce258a47d2ecee45de"

      define_method(:install) do
        bin.install "clitest"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sleipi/cli-t/releases/download/v1.0.0/cli-t_1.0.0_linux_amd64.tar.gz"
      sha256 "a877cabf316ff1bc242175c8cc10bd4f392431bf50e06fbdbd52626bb4cd8685"
      define_method(:install) do
        bin.install "clitest"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sleipi/cli-t/releases/download/v1.0.0/cli-t_1.0.0_linux_arm64.tar.gz"
      sha256 "2e7ac0bc561148905c70a015683f12f4ca5d08c040c6a7b9538261d3a6ae8d89"
      define_method(:install) do
        bin.install "clitest"
      end
    end
  end

  def caveats
    <<~EOS
      CLITest installed! Run 'clitest' to start.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/clitest --version")
  end
end
